'use client'

import { useBudgets } from '@/lib/hooks/useBudgets'

interface Props { from: string; to: string; team?: string }

const ReportSection = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div style={{ marginBottom: '40px' }}>
    <h2 style={{ fontSize: '13px', fontWeight: 600, color: 'var(--colour-text-secondary)', textTransform: 'uppercase', letterSpacing: '0.8px', margin: '0 0 16px', paddingBottom: '8px', borderBottom: '1px solid var(--colour-border)' }}>
      {title}
    </h2>
    {children}
  </div>
)

const BudgetVsActualPreview = ({ from, to }: Props) => {
  const { data: budgets } = useBudgets()

  return (
    <div style={{ color: 'var(--colour-text-primary)', fontFamily: 'monospace' }}>
      <div style={{ marginBottom: '40px', paddingBottom: '24px', borderBottom: '2px solid var(--colour-border)' }}>
        <div style={{ fontSize: '11px', color: 'var(--colour-text-muted)', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '8px' }}>
          CostPrism · Budget vs Actual
        </div>
        <h1 style={{ fontSize: '28px', fontWeight: 700, margin: '0 0 8px', letterSpacing: '-0.5px' }}>Budget vs Actual</h1>
        <div style={{ fontSize: '13px', color: 'var(--colour-text-secondary)' }}>Period: {from} to {to}</div>
      </div>

      <ReportSection title="Budget overview">
        {!budgets || budgets.length === 0 ? (
          <div style={{ fontSize: '13px', color: 'var(--colour-text-muted)' }}>No budgets configured.</div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
            {budgets.map((b) => {
              const spent = 0 // placeholder until George returns actuals
              const pct = Math.min(100, (spent / Number(b.amount)) * 100)
              const colour = pct >= 100 ? 'var(--colour-red)' : pct >= 90 ? 'var(--colour-orange)' : pct >= 70 ? 'var(--colour-yellow)' : 'var(--colour-green)'
              return (
                <div key={b.id} style={{ padding: '16px', background: 'var(--colour-bg-card)', border: '1px solid var(--colour-border)', borderRadius: '10px' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '10px' }}>
                    <div>
                      <div style={{ fontSize: '14px', fontWeight: 600 }}>{b.name}</div>
                      <div style={{ fontSize: '11px', color: 'var(--colour-text-muted)', marginTop: '2px' }}>
                        {b.period.charAt(0) + b.period.slice(1).toLowerCase()} · {b.scopeType}
                      </div>
                    </div>
                    <div style={{ textAlign: 'right' as const }}>
                      <div style={{ fontSize: '14px', fontWeight: 600, color: colour }}>£{spent.toLocaleString()}</div>
                      <div style={{ fontSize: '11px', color: 'var(--colour-text-muted)' }}>of £{Number(b.amount).toLocaleString()}</div>
                    </div>
                  </div>
                  <div style={{ height: '6px', borderRadius: '3px', background: 'var(--colour-border)', overflow: 'hidden' }}>
                    <div style={{ height: '100%', width: `${pct}%`, background: colour, borderRadius: '3px' }} />
                  </div>
                  <div style={{ display: 'flex', gap: '8px', marginTop: '8px' }}>
                    {b.alertThreshold70 && <span style={{ fontSize: '10px', padding: '2px 6px', borderRadius: '4px', background: 'rgba(252,174,30,0.1)', color: 'var(--colour-yellow)', border: '1px solid rgba(252,174,30,0.3)' }}>Alert at 70%</span>}
                    {b.alertThreshold90 && <span style={{ fontSize: '10px', padding: '2px 6px', borderRadius: '4px', background: 'rgba(255,132,0,0.1)', color: 'var(--colour-orange)', border: '1px solid rgba(255,132,0,0.3)' }}>Alert at 90%</span>}
                    {b.alertThreshold100 && <span style={{ fontSize: '10px', padding: '2px 6px', borderRadius: '4px', background: 'rgba(247,49,18,0.1)', color: 'var(--colour-red)', border: '1px solid rgba(247,49,18,0.3)' }}>Alert at 100%</span>}
                  </div>
                </div>
              )
            })}
          </div>
        )}
      </ReportSection>

      <div style={{ marginTop: '40px', paddingTop: '16px', borderTop: '1px solid var(--colour-border)', fontSize: '11px', color: 'var(--colour-text-muted)', display: 'flex', justifyContent: 'space-between' }}>
        <span>Generated by CostPrism</span>
        <span>{new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</span>
      </div>
    </div>
  )
}

export default BudgetVsActualPreview