'use client'

import { useDiscoveredTags, DiscoveredTagKey } from '@/lib/hooks/useTags'

interface Props { from: string; to: string; team?: string }

const ReportSection = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <div style={{ marginBottom: '40px' }}>
    <h2 style={{ fontSize: '13px', fontWeight: 600, color: 'var(--colour-text-secondary)', textTransform: 'uppercase', letterSpacing: '0.8px', margin: '0 0 16px', paddingBottom: '8px', borderBottom: '1px solid var(--colour-border)' }}>
      {title}
    </h2>
    {children}
  </div>
)

const REQUIRED = ['environment', 'team', 'application', 'cost-centre']

const TagCoveragePreview = ({ from, to }: Props) => {
  const { data } = useDiscoveredTags()

  const taggedSpend = data?.discovered_keys.reduce((sum: number, k: DiscoveredTagKey) => sum + k.spend_covered, 0) ?? 0
  const score = data ? Math.round((taggedSpend / data.total_spend) * 100) : 0
  const colour = score >= 80 ? 'var(--colour-green)' : score >= 60 ? 'var(--colour-yellow)' : 'var(--colour-red)'

  return (
    <div style={{ color: 'var(--colour-text-primary)', fontFamily: 'monospace' }}>
      <div style={{ marginBottom: '40px', paddingBottom: '24px', borderBottom: '2px solid var(--colour-border)' }}>
        <div style={{ fontSize: '11px', color: 'var(--colour-text-muted)', textTransform: 'uppercase', letterSpacing: '1px', marginBottom: '8px' }}>
          CostPrism · Tag Coverage Report
        </div>
        <h1 style={{ fontSize: '28px', fontWeight: 700, margin: '0 0 8px', letterSpacing: '-0.5px' }}>Tag Coverage Report</h1>
        <div style={{ fontSize: '13px', color: 'var(--colour-text-secondary)' }}>Period: {from} to {to}</div>
      </div>

      <ReportSection title="Coverage score">
        <div style={{ display: 'flex', alignItems: 'center', gap: '24px', padding: '20px', background: 'var(--colour-bg-card)', border: '1px solid var(--colour-border)', borderRadius: '10px' }}>
          <div style={{ fontSize: '48px', fontWeight: 700, color: colour }}>{score}%</div>
          <div>
            <div style={{ fontSize: '14px', fontWeight: 600, marginBottom: '4px' }}>Spend tag coverage</div>
            <div style={{ fontSize: '12px', color: 'var(--colour-text-secondary)' }}>
              {score >= 80 ? '✓ Good — over 80% of spend is tagged' : score >= 60 ? '⚠ Needs attention — between 60–80% tagged' : '✗ Critical — less than 60% of spend is tagged'}
            </div>
            {data && (
              <div style={{ fontSize: '11px', color: 'var(--colour-text-muted)', marginTop: '4px' }}>
                £{data.untagged_spend.toLocaleString()} untagged spend
              </div>
            )}
          </div>
        </div>
      </ReportSection>

      {data && data.discovered_keys.length > 0 && (
        <ReportSection title="Tag key breakdown">
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr>
                {['Tag key', 'Required', 'Spend covered', 'Resources tagged', 'Variants'].map((h) => (
                  <th key={h} style={{ textAlign: 'left', fontSize: '11px', color: 'var(--colour-text-muted)', fontWeight: 500, paddingBottom: '8px', borderBottom: '1px solid var(--colour-border)' }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {data.discovered_keys.map((key: DiscoveredTagKey, i: number) => (
                <tr key={key.key} style={{ borderBottom: i < data.discovered_keys.length - 1 ? '1px solid var(--colour-border)' : 'none' }}>
                  <td style={{ padding: '10px 0', fontSize: '13px', fontWeight: 500 }}>{key.key}</td>
                  <td style={{ padding: '10px 0', fontSize: '13px' }}>{REQUIRED.includes(key.key) ? '✓' : '—'}</td>
                  <td style={{ padding: '10px 0', fontSize: '13px' }}>£{key.spend_covered.toLocaleString()}</td>
                  <td style={{ padding: '10px 0', fontSize: '13px' }}>{key.resources_tagged.toLocaleString()}</td>
                  <td style={{ padding: '10px 0', fontSize: '13px', color: key.variants_found.length > 1 ? 'var(--colour-yellow)' : 'var(--colour-text-muted)' }}>
                    {key.variants_found.length > 1 ? `⚠ ${key.variants_found.length} variants` : '—'}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </ReportSection>
      )}

      <div style={{ marginTop: '40px', paddingTop: '16px', borderTop: '1px solid var(--colour-border)', fontSize: '11px', color: 'var(--colour-text-muted)', display: 'flex', justifyContent: 'space-between' }}>
        <span>Generated by CostPrism</span>
        <span>{new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</span>
      </div>
    </div>
  )
}

export default TagCoveragePreview